name: picdb
description: "PicDB is a free, anonymously and fast picture storage web application built by Arkynox. Store, organize, and access your images easily from any device."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  lottie: ^2.3.0
  flutter_svg: ^1.0.0
#  permission_handler: ^10.2.0
  flutter_plugin_android_lifecycle: ^2.0.0
  url_launcher: ^6.1.14
  share_plus: ^7.1.0
  loading_indicator: ^3.0.2
  dotted_border: ^2.0.0+1
  image_picker: ^1.0.4
  flutter_upi_india: ^0.0.6
#  cupertino_icons: ^1.0.8
  qr_flutter: ^4.0.0
  toastification: ^2.3.0
  flutter_local_notifications: ^18.0.1
  google_nav_bar: ^5.0.7
  shared_preferences: ^2.5.3
  internet_connection_checker_plus: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  flutter_dropzone: ^4.2.1
  image_cropper: 5.0.0
  photo_view: ^0.15.0
  permission_handler: ^12.0.1
  page_transition: ^2.1.0
  spring_button: ^2.0.0
  animations: ^2.0.8
  shimmer: ^3.0.0
  timezone: ^0.9.2
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Vonique
      fonts:
        - asset: assets/fonts/vonique/basic.ttf
    - family: VoniqueBold
      fonts:
        - asset: assets/fonts/vonique/bold.ttf
    - family: VoniqueBoldItalic
      fonts:
        - asset: assets/fonts/vonique/bold_italic.ttf
    - family: VoniqueItalic
      fonts:
        - asset: assets/fonts/vonique/italic.ttf
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
